name: bdaya_repository_pattern
description: A simple implmentation of the repository pattern used at our company.
version: 3.0.0-dev.1
repository: https://github.com/Bdaya-Dev/Flutter-Repository-Pattern

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  hive: ^1.6.0-nullsafety.2
  rxdart: ^0.26.0
  collection: ^1.15.0-nullsafety.4
