name: bdaya_repository_pattern
description: A simple implmentation of the repository pattern used at our company.
version: 2.0.2
repository: https://github.com/Bdaya-Dev/Flutter-Repository-Pattern

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  hive: ^1.4.4+1  
  rxdart: ^0.25.0
